from flask import Flask, request, jsonify
import os

app = Flask(__name__)

# Read API key from environment variable (set later in Render)
VALID_API_KEY = os.getenv("API_KEY", "my-secret-key-123")

PRODUCTS = [
    {"id": 1, "name": "Quantum Widget", "category": "Gadgets", "price": 19.99, "description": "A compact device for enhancing signal strength.", "life_cycle_status": "Active"},
    {"id": 2, "name": "Gizmo Pro", "category": "Gadgets", "price": 29.50, "description": "Multi-functional gadget with touch controls.", "life_cycle_status": "In Development"},
    {"id": 3, "name": "Thingamajig", "category": "Tools", "price": 9.75, "description": "Versatile tool for precision tasks.", "life_cycle_status": "Active"},
    {"id": 4, "name": "Smart Bulb", "category": "Home", "price": 14.99, "description": "Wi-Fi enabled LED bulb with color options.", "life_cycle_status": "Active"},
    {"id": 5, "name": "Eco Charger", "category": "Electronics", "price": 24.95, "description": "Solar-powered phone charger.", "life_cycle_status": "In Development"},
    {"id": 6, "name": "Flex Hammer", "category": "Tools", "price": 12.50, "description": "Ergonomic hammer with rubber grip.", "life_cycle_status": "Active"},
    {"id": 7, "name": "Nano Drone", "category": "Gadgets", "price": 49.99, "description": "Miniature drone with HD camera.", "life_cycle_status": "Active"},
    {"id": 8, "name": "Therma Mug", "category": "Kitchen", "price": 18.75, "description": "Insulated mug for hot and cold drinks.", "life_cycle_status": "Active"},
    {"id": 9, "name": "VR Headset X", "category": "Electronics", "price": 199.99, "description": "Immersive virtual reality headset.", "life_cycle_status": "In Development"},
    {"id": 10, "name": "Power Drill", "category": "Tools", "price": 59.99, "description": "Cordless drill with multiple speed settings.", "life_cycle_status": "Active"},
    {"id": 11, "name": "Smart Thermostat", "category": "Home", "price": 89.50, "description": "Energy-saving thermostat with app control.", "life_cycle_status": "Active"},
    {"id": 12, "name": "Glow Lamp", "category": "Home", "price": 22.30, "description": "Adjustable brightness desk lamp.", "life_cycle_status": "Discontinued"},
    {"id": 13, "name": "Fitness Tracker", "category": "Wearables", "price": 39.99, "description": "Tracks steps, heart rate, and sleep.", "life_cycle_status": "Active"},
    {"id": 14, "name": "Blender Pro", "category": "Kitchen", "price": 79.99, "description": "High-speed blender for smoothies.", "life_cycle_status": "Active"},
    {"id": 15, "name": "Wireless Mouse", "category": "Electronics", "price": 15.99, "description": "Ergonomic mouse with long battery life.", "life_cycle_status": "Active"},
    {"id": 16, "name": "Camping Stove", "category": "Outdoor", "price": 45.00, "description": "Portable stove for outdoor cooking.", "life_cycle_status": "Active"},
    {"id": 17, "name": "Air Purifier", "category": "Home", "price": 129.99, "description": "HEPA filter for clean indoor air.", "life_cycle_status": "Active"},
    {"id": 18, "name": "Smart Speaker", "category": "Electronics", "price": 69.99, "description": "Voice-activated speaker with AI assistant.", "life_cycle_status": "In Development"},
    {"id": 19, "name": "Yoga Mat", "category": "Fitness", "price": 24.99, "description": "Non-slip mat for yoga and exercise.", "life_cycle_status": "Active"},
    {"id": 20, "name": "Solar Lantern", "category": "Outdoor", "price": 19.50, "description": "Rechargeable lantern for camping.", "life_cycle_status": "Active"},
    {"id": 21, "name": "Coffee Maker", "category": "Kitchen", "price": 49.99, "description": "Programmable drip coffee machine.", "life_cycle_status": "Active"},
    {"id": 22, "name": "Dash Cam", "category": "Electronics", "price": 59.95, "description": "HD dashboard camera for vehicles.", "life_cycle_status": "Active"},
    {"id": 23, "name": "Toolbox Set", "category": "Tools", "price": 89.99, "description": "Complete toolkit for home repairs.", "life_cycle_status": "Active"},
    {"id": 24, "name": "Wireless Earbuds", "category": "Electronics", "price": 39.99, "description": "Noise-canceling earbuds with case.", "life_cycle_status": "Active"},
    {"id": 25, "name": "Portable Grill", "category": "Outdoor", "price": 65.00, "description": "Compact grill for tailgating.", "life_cycle_status": "Active"},
    {"id": 26, "name": "Smart Lock", "category": "Home", "price": 99.99, "description": "Keyless entry lock with app control.", "life_cycle_status": "In Development"},
    {"id": 27, "name": "Electric Kettle", "category": "Kitchen", "price": 29.99, "description": "Fast-boiling kettle with auto shut-off.", "life_cycle_status": "Active"},
    {"id": 28, "name": "Robot Vacuum", "category": "Home", "price": 199.99, "description": "Automated vacuum for pet hair.", "life_cycle_status": "Active"},
    {"id": 29, "name": "Gaming Mouse", "category": "Electronics", "price": 49.99, "description": "Customizable mouse for gaming.", "life_cycle_status": "Active"},
    {"id": 30, "name": "Hiking Backpack", "category": "Outdoor", "price": 79.99, "description": "Water-resistant backpack for hiking.", "life_cycle_status": "Active"},
    {"id": 31, "name": "Smart Watch", "category": "Wearables", "price": 149.99, "description": "Fitness and notification smartwatch.", "life_cycle_status": "Active"},
    {"id": 32, "name": "Cordless Vacuum", "category": "Home", "price": 129.99, "description": "Lightweight vacuum for quick cleanups.", "life_cycle_status": "Active"},
    {"id": 33, "name": "Food Processor", "category": "Kitchen", "price": 89.99, "description": "Multi-function food prep appliance.", "life_cycle_status": "Active"},
    {"id": 34, "name": "Action Camera", "category": "Electronics", "price": 99.99, "description": "Waterproof camera for adventures.", "life_cycle_status": "Active"},
    {"id": 35, "name": "Treadmill", "category": "Fitness", "price": 499.99, "description": "Foldable treadmill with digital display.", "life_cycle_status": "Active"},
    {"id": 36, "name": "Smart Doorbell", "category": "Home", "price": 129.99, "description": "Video doorbell with motion detection.", "life_cycle_status": "In Development"},
    {"id": 37, "name": "Electric Screwdriver", "category": "Tools", "price": 34.99, "description": "Rechargeable screwdriver with bits.", "life_cycle_status": "Active"},
    {"id": 38, "name": "Portable Speaker", "category": "Electronics", "price": 49.99, "description": "Bluetooth speaker with deep bass.", "life_cycle_status": "Active"},
    {"id": 39, "name": "Camping Tent", "category": "Outdoor", "price": 89.99, "description": "4-person tent with rainfly.", "life_cycle_status": "Active"},
    {"id": 40, "name": "Toaster Oven", "category": "Kitchen", "price": 59.99, "description": "Compact oven for baking and toasting.", "life_cycle_status": "Active"},
    {"id": 41, "name": "Smart Plug", "category": "Home", "price": 19.99, "description": "Wi-Fi enabled plug for automation.", "life_cycle_status": "Active"},
    {"id": 42, "name": "Fitness Dumbbells", "category": "Fitness", "price": 49.99, "description": "Adjustable weight dumbbell set.", "life_cycle_status": "Active"},
    {"id": 43, "name": "Laptop Stand", "category": "Electronics", "price": 29.99, "description": "Ergonomic stand for laptops.", "life_cycle_status": "Active"},
    {"id": 44, "name": "Sleeping Bag", "category": "Outdoor", "price": 39.99, "description": "Warm sleeping bag for cold weather.", "life_cycle_status": "Active"},
    {"id": 45, "name": "Air Fryer", "category": "Kitchen", "price": 79.99, "description": "Healthy frying with minimal oil.", "life_cycle_status": "Active"},
    {"id": 46, "name": "Smart Scale", "category": "Fitness", "price": 34.99, "description": "Body composition scale with app.", "life_cycle_status": "Active"},
    {"id": 47, "name": "Cordless Saw", "category": "Tools", "price": 99.99, "description": "Battery-powered saw for woodworking.", "life_cycle_status": "Active"},
    {"id": 48, "name": "Noise Machine", "category": "Home", "price": 29.99, "description": "White noise machine for sleep.", "life_cycle_status": "Active"},
    {"id": 49, "name": "Gaming Keyboard", "category": "Electronics", "price": 69.99, "description": "RGB mechanical keyboard.", "life_cycle_status": "Active"},
    {"id": 50, "name": "Cooler Bag", "category": "Outdoor", "price": 24.99, "description": "Insulated bag for picnics.", "life_cycle_status": "Active"},
    {"id": 51, "name": "Electric Blanket", "category": "Home", "price": 49.99, "description": "Heated blanket with timer.", "life_cycle_status": "Active"},
    {"id": 52, "name": "Smart Fridge", "category": "Kitchen", "price": 999.99, "description": "Refrigerator with touchscreen display.", "life_cycle_status": "In Development"},
    {"id": 53, "name": "Power Bank", "category": "Electronics", "price": 29.99, "description": "High-capacity portable charger.", "life_cycle_status": "Active"},
    {"id": 54, "name": "Hedge Trimmer", "category": "Tools", "price": 79.99, "description": "Cordless trimmer for gardening.", "life_cycle_status": "Active"},
    {"id": 55, "name": "Smart Mirror", "category": "Home", "price": 199.99, "description": "Interactive mirror with fitness apps.", "life_cycle_status": "In Development"},
    {"id": 56, "name": "Kettlebell", "category": "Fitness", "price": 39.99, "description": "Cast iron kettlebell for workouts.", "life_cycle_status": "Active"},
    {"id": 57, "name": "Dash Blender", "category": "Kitchen", "price": 49.99, "description": "Single-serve blender for quick drinks.", "life_cycle_status": "Active"},
    {"id": 58, "name": "Smart Glasses", "category": "Wearables", "price": 249.99, "description": "Augmented reality glasses.", "life_cycle_status": "In Development"},
    {"id": 59, "name": "Leaf Blower", "category": "Tools", "price": 89.99, "description": "Electric blower for yard cleanup.", "life_cycle_status": "Active"},
    {"id": 60, "name": "Humidifier", "category": "Home", "price": 39.99, "description": "Ultrasonic humidifier for dry air.", "life_cycle_status": "Active"},
    {"id": 61, "name": "Smart Kettle", "category": "Kitchen", "price": 59.99, "description": "App-controlled kettle with presets.", "life_cycle_status": "In Development"},
    {"id": 62, "name": "Dashcam Pro", "category": "Electronics", "price": 79.99, "description": "4K dashcam with night vision.", "life_cycle_status": "Active"},
    {"id": 63, "name": "Camp Chair", "category": "Outdoor", "price": 29.99, "description": "Foldable chair for camping.", "life_cycle_status": "Active"},
    {"id": 64, "name": "Smart Fan", "category": "Home", "price": 69.99, "description": "Wi-Fi enabled fan with remote.", "life_cycle_status": "Active"},
    {"id": 65, "name": "Rowing Machine", "category": "Fitness", "price": 299.99, "description": "Compact rower for home workouts.", "life_cycle_status": "Active"},
    {"id": 66, "name": "LED Strip", "category": "Home", "price": 19.99, "description": "Color-changing LED strip lights.", "life_cycle_status": "Active"},
    {"id": 67, "name": "Cordless Sander", "category": "Tools", "price": 69.99, "description": "Battery-powered sander for projects.", "life_cycle_status": "Active"},
    {"id": 68, "name": "Smart Camera", "category": "Home", "price": 89.99, "description": "Security camera with cloud storage.", "life_cycle_status": "Active"},
    {"id": 69, "name": "Espresso Machine", "category": "Kitchen", "price": 149.99, "description": "Compact espresso maker with frother.", "life_cycle_status": "Active"},
    {"id": 70, "name": "Fitness Bike", "category": "Fitness", "price": 249.99, "description": "Stationary bike with resistance levels.", "life_cycle_status": "Active"},
    {"id": 71, "name": "Smart Alarm", "category": "Home", "price": 39.99, "description": "Alarm clock with sunrise simulation.", "life_cycle_status": "Active"},
    {"id": 72, "name": "Portable Monitor", "category": "Electronics", "price": 129.99, "description": "USB-C powered second screen.", "life_cycle_status": "Active"},
    {"id": 73, "name": "Hammock", "category": "Outdoor", "price": 49.99, "description": "Lightweight hammock for camping.", "life_cycle_status": "Active"},
    {"id": 74, "name": "Rice Cooker", "category": "Kitchen", "price": 39.99, "description": "Multi-function rice and grain cooker.", "life_cycle_status": "Active"},
    {"id": 75, "name": "Smart Blinds", "category": "Home", "price": 149.99, "description": "Automated blinds with app control.", "life_cycle_status": "In Development"},
    {"id": 76, "name": "Power Washer", "category": "Tools", "price": 199.99, "description": "High-pressure washer for cleaning.", "life_cycle_status": "Active"},
    {"id": 77, "name": "Smart Ring", "category": "Wearables", "price": 99.99, "description": "Fitness and sleep tracking ring.", "life_cycle_status": "In Development"},
    {"id": 78, "name": "Electric Grill", "category": "Kitchen", "price": 89.99, "description": "Indoor grill with adjustable heat.", "life_cycle_status": "Active"},
    {"id": 79, "name": "Smart Sprinkler", "category": "Outdoor", "price": 129.99, "description": "Wi-Fi controlled sprinkler system.", "life_cycle_status": "Active"},
    {"id": 80, "name": "Massage Gun", "category": "Fitness", "price": 99.99, "description": "Percussive therapy for muscle recovery.", "life_cycle_status": "Active"},
    {"id": 81, "name": "Smart Oven", "category": "Kitchen", "price": 249.99, "description": "Wi-Fi enabled oven with recipes.", "life_cycle_status": "In Development"},
    {"id": 82, "name": "Laser Level", "category": "Tools", "price": 49.99, "description": "Self-leveling laser for construction.", "life_cycle_status": "Active"},
    {"id": 83, "name": "Smart Light Switch", "category": "Home", "price": 29.99, "description": "Wi-Fi enabled light switch.", "life_cycle_status": "Active"},
    {"id": 84, "name": "Gaming Headset", "category": "Electronics", "price": 79.99, "description": "Surround sound headset for gaming.", "life_cycle_status": "Active"},
    {"id": 85, "name": "Backpacking Stove", "category": "Outdoor", "price": 39.99, "description": "Lightweight stove for backpacking.", "life_cycle_status": "Active"},
    {"id": 86, "name": "Slow Cooker", "category": "Kitchen", "price": 49.99, "description": "Programmable cooker for meals.", "life_cycle_status": "Active"},
    {"id": 87, "name": "Smart Projector", "category": "Electronics", "price": 299.99, "description": "Portable projector with streaming.", "life_cycle_status": "In Development"},
    {"id": 88, "name": "Resistance Bands", "category": "Fitness", "price": 19.99, "description": "Set of bands for strength training.", "life_cycle_status": "Active"},
    {"id": 89, "name": "Smart Garage", "category": "Home", "price": 99.99, "description": "App-controlled garage door opener.", "life_cycle_status": "Active"},
    {"id": 90, "name": "Cordless Jigsaw", "category": "Tools", "price": 79.99, "description": "Battery-powered jigsaw for cutting.", "life_cycle_status": "Active"},
    {"id": 91, "name": "Smart Earplugs", "category": "Wearables", "price": 49.99, "description": "Noise-filtering earplugs with app.", "life_cycle_status": "In Development"},
    {"id": 92, "name": "Ice Maker", "category": "Kitchen", "price": 99.99, "description": "Countertop ice maker for parties.", "life_cycle_status": "Active"},
    {"id": 93, "name": "Smart Humidifier", "category": "Home", "price": 79.99, "description": "App-controlled humidifier.", "life_cycle_status": "Active"},
    {"id": 94, "name": "Camping Lantern", "category": "Outdoor", "price": 29.99, "description": "Rechargeable lantern with SOS mode.", "life_cycle_status": "Active"},
    {"id": 95, "name": "Smart Toaster", "category": "Kitchen", "price": 69.99, "description": "Toaster with digital settings.", "life_cycle_status": "In Development"},
    {"id": 96, "name": "Fitness Roller", "category": "Fitness", "price": 24.99, "description": "Foam roller for muscle recovery.", "life_cycle_status": "Active"},
    {"id": 97, "name": "Smart Thermometer", "category": "Home", "price": 39.99, "description": "Wi-Fi enabled indoor thermometer.", "life_cycle_status": "Active"},
    {"id": 98, "name": "Cordless Blower", "category": "Tools", "price": 69.99, "description": "Battery-powered blower for debris.", "life_cycle_status": "Active"},
    {"id": 99, "name": "Smart Headphones", "category": "Electronics", "price": 149.99, "description": "Noise-canceling headphones with AI.", "life_cycle_status": "In Development"},
    {"id": 100, "name": "Portable Hammock", "category": "Outdoor", "price": 59.99, "description": "Quick-setup hammock for travel.", "life_cycle_status": "Active"},
    {
        "id": 1,
        "name": "ST-240082",
        "category": "Actuator",
        "price": 45.60,
        "description": "Reinforced pipe fitting with corrosion-resistant coating.",
        "life_cycle_status": "Active"
    },
    {
        "id": 2,
        "name": "ST-240085",
        "category": "Actuator",
        "price": 48.90,
        "description": "Heavy duty pipe fitting with pressure relief capability.",
        "life_cycle_status": "Prototype"
    },
    {
        "id": 3,
        "name": "ST-240090",
        "category": "Actuator",
        "price": 47.25,
        "description": "Pipe fitting for high-pressure industrial applications.",
        "life_cycle_status": "Active"
    },
    {
        "id": 4,
        "name": "PE-254830",
        "category": "Compressor",
        "price": 6.75,
        "description": "High temperature sealing ring made from silicone compound.",
        "life_cycle_status": "Active"
    },
    {
        "id": 5,
        "name": "PE-254835",
        "category": "Compressor",
        "price": 7.20,
        "description": "Sealing ring designed for thermal expansion resistance.",
        "life_cycle_status": "Prototype"
    },
    {
        "id": 6,
        "name": "PE-254838",
        "category": "Compressor",
        "price": 6.95,
        "description": "Durable sealing ring suitable for continuous heat cycles.",
        "life_cycle_status": "Active"
    },
    {
        "id": 7,
        "name": "PE-735546",
        "category": "Valve",
        "price": 6.90,
        "description": "High temperature sealing ring with fluorocarbon coating.",
        "life_cycle_status": "Active"
    },
    {
        "id": 8,
        "name": "PE-735550",
        "category": "Valve",
        "price": 7.50,
        "description": "Graphite-based sealing ring for extreme valve applications.",
        "life_cycle_status": "Prototype"
    },
    {
        "id": 9,
        "name": "PE-735552",
        "category": "Valve",
        "price": 7.10,
        "description": "Heat-resistant sealing ring with reinforced carbon layer.",
        "life_cycle_status": "Active"
    },
    {
        "id": 10,
        "name": "PE-735555",
        "category": "Valve",
        "price": 7.80,
        "description": "Valve sealing ring optimized for chemical resistance.",
        "life_cycle_status": "Prototype"
    },
    {
        "id": 11,
        "name": "ME-65568",
        "category": "Compressor",
        "price": 2.35,
        "description": "Electrical connector terminal with silver plating for enhanced conductivity.",
        "life_cycle_status": "Active"
    },
    {
        "id": 12,
        "name": "ME-65570",
        "category": "Compressor",
        "price": 2.95,
        "description": "Heavy-duty electrical connector terminal with heat-resistant housing.",
        "life_cycle_status": "Prototype"
    },
    {
        "id": 13,
        "name": "ME-65572",
        "category": "Compressor",
        "price": 2.60,
        "description": "Compact terminal optimized for low-loss power transfer.",
        "life_cycle_status": "Active"
    },
    {
        "id": 14,
        "name": "GP-231",
        "category": "Hydraulic",
        "price": 125.80,
        "description": "High pressure pump with stainless steel impeller.",
        "life_cycle_status": "Active"
    },
    {
        "id": 15,
        "name": "GP-235",
        "category": "Hydraulic",
        "price": 138.40,
        "description": "High pressure pump featuring variable flow control system.",
        "life_cycle_status": "Prototype"
    },
    {
        "id": 16,
        "name": "GP-240",
        "category": "Hydraulic",
        "price": 132.75,
        "description": "Compact high pressure pump for closed hydraulic circuits.",
        "life_cycle_status": "Active"
    },
    {
        "id": 17,
        "name": "GP-245",
        "category": "Hydraulic",
        "price": 140.10,
        "description": "High pressure pump with ceramic-coated pistons for extended life.",
        "life_cycle_status": "Prototype"
    }
]


500_Products = [
  {"id": 1, "Part-Number": "GL-724589", "category": "Seal", "description": "Stainless steel filtration unit with reinforced gaskets", "life_cycle_status": "Active"},
  {"id": 2, "Part-Number": "ST-101456", "category": "Valve", "description": "Stainless steel filtration unit for high flow", "life_cycle_status": "Active"},
  {"id": 3, "Part-Number": "HY-288145", "category": "Sensor", "description": "Air compressor for process plant applications", "life_cycle_status": "Active"},
  {"id": 4, "Part-Number": "EN-310234", "category": "Seal", "description": "Electrical connector terminal with sealing capability", "life_cycle_status": "Active"},
  {"id": 5, "Part-Number": "TH-98567", "category": "Pipe", "description": "Flow regulator for chemical line processing", "life_cycle_status": "Active"},
  {"id": 6, "Part-Number": "OP-110789", "category": "Valve", "description": "Flow regulator for chemical line control", "life_cycle_status": "Active"},
  {"id": 7, "Part-Number": "GL-478234", "category": "Regulator", "description": "Industrial hydraulic pump with pressure control", "life_cycle_status": "Active"},
  {"id": 8, "Part-Number": "TH-86912", "category": "Valve", "description": "High pressure control valve assembly", "life_cycle_status": "Active"},
  {"id": 9, "Part-Number": "ST-240356", "category": "Actuator", "description": "Heavy duty pipe fitting with actuator mount", "life_cycle_status": "Active"},
  {"id": 10, "Part-Number": "HY-659821", "category": "Pipe", "description": "Digital flow sensor module for pipeline monitoring", "life_cycle_status": "Active"},
  {"id": 11, "Part-Number": "GL-767123", "category": "Regulator", "description": "Air compressor for process plant regulation", "life_cycle_status": "Active"},
  {"id": 12, "Part-Number": "ME-240187", "category": "Actuator", "description": "Flow regulator for chemical line automation", "life_cycle_status": "Active"},
  {"id": 13, "Part-Number": "EN-948456", "category": "Connector", "description": "Air compressor for process plant connectivity", "life_cycle_status": "Active"},
  {"id": 14, "Part-Number": "ME-304912", "category": "Valve", "description": "High pressure control valve mechanism", "life_cycle_status": "Active"},
  {"id": 15, "Part-Number": "HY-580934", "category": "Actuator", "description": "High pressure control valve actuator", "life_cycle_status": "Active"},
  {"id": 16, "Part-Number": "ST-158289", "category": "Compressor", "description": "High pressure control valve compressor unit", "life_cycle_status": "Active"},
  {"id": 17, "Part-Number": "PE-194178", "category": "Compressor", "description": "Digital flow sensor module with compression", "life_cycle_status": "Active"},
  {"id": 18, "Part-Number": "EN-565334", "category": "Compressor", "description": "High pressure control valve compression system", "life_cycle_status": "Active"},
  {"id": 19, "Part-Number": "TH-578091", "category": "Compressor", "description": "Heavy duty pipe fitting compressor compatible", "life_cycle_status": "Active"},
  {"id": 20, "Part-Number": "GL-531067", "category": "Seal", "description": "High pressure control valve sealing system", "life_cycle_status": "Active"},
  {"id": 21, "Part-Number": "OP-443124", "category": "Pump", "description": "High temperature sealing ring for pumps", "life_cycle_status": "Active"},
  {"id": 22, "Part-Number": "TH-450589", "category": "Actuator", "description": "High temperature sealing ring actuator grade", "life_cycle_status": "Active"},
  {"id": 23, "Part-Number": "ST-24678", "category": "Pipe", "description": "Digital flow sensor module pipe mount", "life_cycle_status": "Active"},
  {"id": 24, "Part-Number": "PR-482567", "category": "Connector", "description": "Stainless steel filtration unit connector", "life_cycle_status": "Active"},
  {"id": 25, "Part-Number": "PE-970489", "category": "Filter", "description": "Heavy duty pipe fitting with filter", "life_cycle_status": "Active"},
  {"id": 26, "Part-Number": "AE-265812", "category": "Connector", "description": "Electric actuator assembly connector module", "life_cycle_status": "Active"},
  {"id": 27, "Part-Number": "HY-208901", "category": "Seal", "description": "Stainless steel filtration unit sealed type", "life_cycle_status": "Active"},
  {"id": 28, "Part-Number": "HY-501345", "category": "Compressor", "description": "High pressure control valve with compressor", "life_cycle_status": "Active"},
  {"id": 29, "Part-Number": "HY-884467", "category": "Regulator", "description": "High pressure control valve regulator", "life_cycle_status": "Active"},
  {"id": 30, "Part-Number": "PR-832534", "category": "Sensor", "description": "Air compressor for process plant sensing", "life_cycle_status": "Active"},
  {"id": 31, "Part-Number": "ST-810523", "category": "Compressor", "description": "Stainless steel filtration unit compressor", "life_cycle_status": "Active"},
  {"id": 32, "Part-Number": "PE-372967", "category": "Sensor", "description": "Digital flow sensor module advanced", "life_cycle_status": "Active"},
  {"id": 33, "Part-Number": "HY-311723", "category": "Sensor", "description": "Electrical connector terminal sensor type", "life_cycle_status": "Active"},
  {"id": 34, "Part-Number": "HY-220034", "category": "Regulator", "description": "Stainless steel filtration unit regulator", "life_cycle_status": "Active"},
  {"id": 35, "Part-Number": "GL-206101", "category": "Sensor", "description": "Stainless steel filtration unit with sensor", "life_cycle_status": "Active"},
  {"id": 36, "Part-Number": "OP-887092", "category": "Connector", "description": "Flow regulator for chemical line connector", "life_cycle_status": "Active"},
  {"id": 37, "Part-Number": "AE-109845", "category": "Compressor", "description": "High temperature sealing ring compressor", "life_cycle_status": "Active"},
  {"id": 38, "Part-Number": "GL-766389", "category": "Actuator", "description": "Stainless steel filtration unit actuator", "life_cycle_status": "Active"},
  {"id": 39, "Part-Number": "PR-486401", "category": "Pump", "description": "Electrical connector terminal pump grade", "life_cycle_status": "Active"},
  {"id": 40, "Part-Number": "TH-238167", "category": "Valve", "description": "Electric actuator assembly valve control", "life_cycle_status": "Active"},
  {"id": 41, "Part-Number": "TH-355998", "category": "Seal", "description": "Industrial hydraulic pump sealing system", "life_cycle_status": "Active"},
  {"id": 42, "Part-Number": "HY-926567", "category": "Pipe", "description": "Electrical connector terminal pipe mount", "life_cycle_status": "Active"},
  {"id": 43, "Part-Number": "ST-577612", "category": "Compressor", "description": "Stainless steel filtration unit compressor type", "life_cycle_status": "Active"},
  {"id": 44, "Part-Number": "TH-557201", "category": "Pump", "description": "Flow regulator for chemical line pump", "life_cycle_status": "Active"},
  {"id": 45, "Part-Number": "HY-267018", "category": "Pipe", "description": "Heavy duty pipe fitting standard", "life_cycle_status": "Active"},
  {"id": 46, "Part-Number": "GL-245891", "category": "Actuator", "description": "Heavy duty pipe fitting actuator type", "life_cycle_status": "Active"},
  {"id": 47, "Part-Number": "HY-804421", "category": "Actuator", "description": "High temperature sealing ring actuator", "life_cycle_status": "Active"},
  {"id": 48, "Part-Number": "ST-872689", "category": "Pump", "description": "Air compressor for process plant pump", "life_cycle_status": "Active"},
  {"id": 49, "Part-Number": "GL-952534", "category": "Valve", "description": "Heavy duty pipe fitting valve assembly", "life_cycle_status": "Active"},
  {"id": 50, "Part-Number": "GL-75689", "category": "Filter", "description": "High pressure control valve filter", "life_cycle_status": "Active"},
  {"id": 51, "Part-Number": "ABH-10929-I", "category": "Gadgets", "description": "Multi-functional gadget with touch controls.", "life_cycle_status": "In Development"},
  {"id": 52, "Part-Number": "ST-445821", "category": "Valve", "description": "Pressure relief valve for industrial systems", "life_cycle_status": "Active"},
  {"id": 53, "Part-Number": "EN-772341", "category": "Connector", "description": "Terminal connector block assembly", "life_cycle_status": "Active"},
  {"id": 54, "Part-Number": "HY-398745", "category": "Pump", "description": "Centrifugal pump for chemical processing", "life_cycle_status": "Active"},
  {"id": 55, "Part-Number": "GL-881923", "category": "Filter", "description": "Stainless mesh filtration assembly", "life_cycle_status": "Active"},
  {"id": 56, "Part-Number": "TH-229841", "category": "Regulator", "description": "Pneumatic pressure regulator unit", "life_cycle_status": "Active"},
  {"id": 57, "Part-Number": "OP-667234", "category": "Sensor", "description": "Temperature sensor for process monitoring", "life_cycle_status": "Active"},
  {"id": 58, "Part-Number": "ME-551892", "category": "Actuator", "description": "Pneumatic actuator with position feedback", "life_cycle_status": "Active"},
  {"id": 59, "Part-Number": "PR-334578", "category": "Seal", "description": "PTFE sealing ring high temperature", "life_cycle_status": "Active"},
  {"id": 60, "Part-Number": "AE-778912", "category": "Compressor", "description": "Rotary screw air compressor unit", "life_cycle_status": "Active"},
  {"id": 61, "Part-Number": "ST-992341", "category": "Pipe", "description": "Stainless steel pipe coupling", "life_cycle_status": "Active"},
  {"id": 62, "Part-Number": "HY-445623", "category": "Valve", "description": "Ball valve with pneumatic actuator", "life_cycle_status": "Active"},
  {"id": 63, "Part-Number": "GL-123789", "category": "Connector", "description": "Quick disconnect coupling system", "life_cycle_status": "Active"},
  {"id": 64, "Part-Number": "EN-556901", "category": "Sensor", "description": "Proximity sensor inductive type", "life_cycle_status": "Active"},
  {"id": 65, "Part-Number": "TH-881234", "category": "Filter", "description": "Coalescing filter element replacement", "life_cycle_status": "Active"},
  {"id": 66, "Part-Number": "PE-778456", "category": "Pump", "description": "Diaphragm pump chemical resistant", "life_cycle_status": "Active"},
  {"id": 67, "Part-Number": "OP-334812", "category": "Regulator", "description": "Back pressure regulator assembly", "life_cycle_status": "Active"},
  {"id": 68, "Part-Number": "HY-667234", "category": "Seal", "description": "Mechanical seal cartridge assembly", "life_cycle_status": "Active"},
  {"id": 69, "Part-Number": "GL-998812", "category": "Actuator", "description": "Electric linear actuator heavy duty", "life_cycle_status": "Active"},
  {"id": 70, "Part-Number": "ST-445678", "category": "Compressor", "description": "Piston air compressor industrial grade", "life_cycle_status": "Active"},
  {"id": 71, "Part-Number": "ME-112389", "category": "Valve", "description": "Butterfly valve with lever operator", "life_cycle_status": "Active"},
  {"id": 72, "Part-Number": "PR-889234", "category": "Connector", "description": "Flanged pipe connector assembly", "life_cycle_status": "Active"},
  {"id": 73, "Part-Number": "AE-556712", "category": "Sensor", "description": "Pressure transmitter digital output", "life_cycle_status": "Active"},
  {"id": 74, "Part-Number": "TH-334891", "category": "Pipe", "description": "Schedule 40 pipe fitting elbow", "life_cycle_status": "Active"},
  {"id": 75, "Part-Number": "HY-221456", "category": "Filter", "description": "Hydraulic return line filter", "life_cycle_status": "Active"},
  {"id": 76, "Part-Number": "GL-667823", "category": "Pump", "description": "Gear pump positive displacement", "life_cycle_status": "Active"},
  {"id": 77, "Part-Number": "EN-998234", "category": "Regulator", "description": "Dome loaded pressure regulator", "life_cycle_status": "Active"},
  {"id": 78, "Part-Number": "OP-112567", "category": "Seal", "description": "O-ring seal kit viton material", "life_cycle_status": "Active"},
  {"id": 79, "Part-Number": "ST-778934", "category": "Actuator", "description": "Rotary actuator rack and pinion", "life_cycle_status": "Active"},
  {"id": 80, "Part-Number": "HY-334756", "category": "Compressor", "description": "Oil-free scroll compressor unit", "life_cycle_status": "Active"},
  {"id": 81, "Part-Number": "ME-889671", "category": "Valve", "description": "Gate valve rising stem type", "life_cycle_status": "Active"},
  {"id": 82, "Part-Number": "GL-445982", "category": "Connector", "description": "Threaded pipe connector brass", "life_cycle_status": "Active"},
  {"id": 83, "Part-Number": "PR-667145", "category": "Sensor", "description": "Level sensor ultrasonic type", "life_cycle_status": "Active"},
  {"id": 84, "Part-Number": "TH-998723", "category": "Pipe", "description": "Pipe support bracket assembly", "life_cycle_status": "Active"},
  {"id": 85, "Part-Number": "AE-334589", "category": "Filter", "description": "Particulate filter cartridge replacement", "life_cycle_status": "Active"},
  {"id": 86, "Part-Number": "HY-556891", "category": "Pump", "description": "Submersible pump stainless steel", "life_cycle_status": "Active"},
  {"id": 87, "Part-Number": "EN-112734", "category": "Regulator", "description": "Flow control regulator needle valve", "life_cycle_status": "Active"},
  {"id": 88, "Part-Number": "ST-667423", "category": "Seal", "description": "Split seal retrofit design", "life_cycle_status": "Active"},
  {"id": 89, "Part-Number": "OP-889756", "category": "Actuator", "description": "Hydraulic actuator double acting", "life_cycle_status": "Active"},
  {"id": 90, "Part-Number": "GL-223891", "category": "Compressor", "description": "Reciprocating compressor two stage", "life_cycle_status": "Active"},
  {"id": 91, "Part-Number": "HY-778534", "category": "Valve", "description": "Check valve swing type", "life_cycle_status": "Active"},
  {"id": 92, "Part-Number": "ME-445612", "category": "Connector", "description": "Compression fitting tube connector", "life_cycle_status": "Active"},
  {"id": 93, "Part-Number": "TH-667289", "category": "Sensor", "description": "Flow meter electromagnetic type", "life_cycle_status": "Active"},
  {"id": 94, "Part-Number": "PR-334901", "category": "Pipe", "description": "Flexible hose assembly braided", "life_cycle_status": "Active"},
  {"id": 95, "Part-Number": "AE-889456", "category": "Filter", "description": "Air filter regulator lubricator combo", "life_cycle_status": "Active"},
  {"id": 96, "Part-Number": "GL-556723", "category": "Pump", "description": "Peristaltic pump dosing system", "life_cycle_status": "Active"},
  {"id": 97, "Part-Number": "ST-112689", "category": "Regulator", "description": "Vacuum regulator precision control", "life_cycle_status": "Active"},
  {"id": 98, "Part-Number": "EN-998567", "category": "Seal", "description": "Gasket sheet material EPDM", "life_cycle_status": "Active"},
  {"id": 99, "Part-Number": "HY-223712", "category": "Actuator", "description": "Solenoid actuator fast response", "life_cycle_status": "Active"},
  {"id": 100, "Part-Number": "OP-778945", "category": "Compressor", "description": "Centrifugal compressor multi-stage", "life_cycle_status": "Active"},
  {"id": 101, "Part-Number": "ME-667834", "category": "Valve", "description": "Globe valve threaded bonnet", "life_cycle_status": "Active"},
  {"id": 102, "Part-Number": "TH-334512", "category": "Connector", "description": "Electrical terminal block enclosure", "life_cycle_status": "Active"},
  {"id": 103, "Part-Number": "GL-889623", "category": "Sensor", "description": "Vibration sensor accelerometer type", "life_cycle_status": "Active"},
  {"id": 104, "Part-Number": "PR-112478", "category": "Pipe", "description": "Pipe reducer bushing threaded", "life_cycle_status": "Active"},
  {"id": 105, "Part-Number": "HY-445789", "category": "Filter", "description": "Suction strainer basket type", "life_cycle_status": "Active"},
  {"id": 106, "Part-Number": "AE-667912", "category": "Pump", "description": "Vertical inline pump bronze fitted", "life_cycle_status": "Active"},
  {"id": 107, "Part-Number": "ST-998234", "category": "Regulator", "description": "Pressure reducing valve pilot operated", "life_cycle_status": "Active"},
  {"id": 108, "Part-Number": "EN-334678", "category": "Seal", "description": "Packing gland seal assembly", "life_cycle_status": "Active"},
  {"id": 109, "Part-Number": "OP-556891", "category": "Actuator", "description": "Spring return actuator fail safe", "life_cycle_status": "Active"},
  {"id": 110, "Part-Number": "GL-112745", "category": "Compressor", "description": "Scroll compressor hermetic sealed", "life_cycle_status": "Active"},
  {"id": 111, "Part-Number": "HY-889523", "category": "Valve", "description": "Plug valve lubricated sleeve", "life_cycle_status": "Active"},
  {"id": 112, "Part-Number": "ME-223867", "category": "Connector", "description": "Hose barb connector stainless", "life_cycle_status": "Active"},
  {"id": 113, "Part-Number": "TH-778412", "category": "Sensor", "description": "Conductivity sensor probe type", "life_cycle_status": "Active"},
  {"id": 114, "Part-Number": "PR-667523", "category": "Pipe", "description": "Expansion joint bellows type", "life_cycle_status": "Active"},
  {"id": 115, "Part-Number": "AE-334789", "category": "Filter", "description": "Strainer Y-type threaded", "life_cycle_status": "Active"},
  {"id": 116, "Part-Number": "GL-998645", "category": "Pump", "description": "Turbine pump deep well type", "life_cycle_status": "Active"},
  {"id": 117, "Part-Number": "ST-445712", "category": "Regulator", "description": "Temperature regulator self-actuated", "life_cycle_status": "Active"},
  {"id": 118, "Part-Number": "HY-667889", "category": "Seal", "description": "Lip seal single spring loaded", "life_cycle_status": "Active"},
  {"id": 119, "Part-Number": "EN-112823", "category": "Actuator", "description": "Vane actuator quarter turn", "life_cycle_status": "Active"},
  {"id": 120, "Part-Number": "OP-889534", "category": "Compressor", "description": "Diaphragm compressor oil-free", "life_cycle_status": "Active"},
  {"id": 121, "Part-Number": "ME-556734", "category": "Valve", "description": "Diaphragm valve weir type", "life_cycle_status": "Active"},
  {"id": 122, "Part-Number": "GL-334891", "category": "Connector", "description": "Push-to-connect fitting composite", "life_cycle_status": "Active"},
  {"id": 123, "Part-Number": "TH-112589", "category": "Sensor", "description": "pH sensor glass electrode", "life_cycle_status": "Active"},
  {"id": 124, "Part-Number": "PR-778923", "category": "Pipe", "description": "Pipe clamp saddle type", "life_cycle_status": "Active"},
  {"id": 125, "Part-Number": "HY-998456", "category": "Filter", "description": "Duplex basket strainer switchover", "life_cycle_status": "Active"},
  {"id": 126, "Part-Number": "AE-223712", "category": "Pump", "description": "Progressing cavity pump eccentric rotor", "life_cycle_status": "Active"},
  {"id": 127, "Part-Number": "ST-667545", "category": "Regulator", "description": "Differential pressure regulator", "life_cycle_status": "Active"},
  {"id": 128, "Part-Number": "EN-445823", "category": "Seal", "description": "V-ring seal axial type", "life_cycle_status": "Active"},
  {"id": 129, "Part-Number": "OP-334678", "category": "Actuator", "description": "Pneumatic cylinder ISO standard", "life_cycle_status": "Active"},
  {"id": 130, "Part-Number": "GL-889712", "category": "Compressor", "description": "Liquid ring compressor vacuum pump", "life_cycle_status": "Active"},
  {"id": 131, "Part-Number": "HY-112934", "category": "Valve", "description": "Pinch valve air operated", "life_cycle_status": "Active"},
  {"id": 132, "Part-Number": "ME-998678", "category": "Connector", "description": "Camlock coupling aluminum", "life_cycle_status": "Active"},
  {"id": 133, "Part-Number": "TH-556812", "category": "Sensor", "description": "Turbidity sensor optical", "life_cycle_status": "Active"},
  {"id": 134, "Part-Number": "PR-223945", "category": "Pipe", "description": "Pipe tee junction fitting", "life_cycle_status": "Active"},
  {"id": 135, "Part-Number": "AE-778634", "category": "Filter", "description": "Membrane filter cartridge pleated", "life_cycle_status": "Active"},
  {"id": 136, "Part-Number": "GL-445867", "category": "Pump", "description": "Magnetic drive pump sealless", "life_cycle_status": "Active"},
  {"id": 137, "Part-Number": "ST-334723", "category": "Regulator", "description": "Relief valve spring loaded", "life_cycle_status": "Active"},
  {"id": 138, "Part-Number": "HY-667512", "category": "Seal", "description": "Rotary shaft seal double lip", "life_cycle_status": "Active"},
  {"id": 139, "Part-Number": "EN-889745", "category": "Actuator", "description": "Electro-hydraulic actuator servo", "life_cycle_status": "Active"},
  {"id": 140, "Part-Number": "OP-112678", "category": "Compressor", "description": "Axial compressor high pressure", "life_cycle_status": "Active"},
  {"id": 141, "Part-Number": "ME-778912", "category": "Valve", "description": "Needle valve precision metering", "life_cycle_status": "Active"},
  {"id": 142, "Part-Number": "GL-556834", "category": "Connector", "description": "Sanitary tri-clamp fitting", "life_cycle_status": "Active"},
  {"id": 143, "Part-Number": "TH-998567", "category": "Sensor", "description": "Radar level sensor non-contact", "life_cycle_status": "Active"},
  {"id": 144, "Part-Number": "PR-445689", "category": "Pipe", "description": "Pipe cap end closure", "life_cycle_status": "Active"},
  {"id": 145, "Part-Number": "HY-334812", "category": "Filter", "description": "Backwash filter automatic cleaning", "life_cycle_status": "Active"},
  {"id": 146, "Part-Number": "AE-889567", "category": "Pump", "description": "Canned motor pump hermetic", "life_cycle_status": "Active"},
  {"id": 147, "Part-Number": "ST-112734", "category": "Regulator", "description": "Proportional pressure regulator", "life_cycle_status": "Active"},
  {"id": 148, "Part-Number": "EN-667823", "category": "Seal", "description": "Quad ring seal square profile", "life_cycle_status": "Active"},
  {"id": 149, "Part-Number": "OP-998412", "category": "Actuator", "description": "Piezoelectric actuator precision", "life_cycle_status": "Active"},
  {"id": 150, "Part-Number": "GL-223756", "category": "Compressor", "description": "Turbo compressor high speed", "life_cycle_status": "Active"},
  {"id": 151, "Part-Number": "HY-778923", "category": "Valve", "description": "Sampling valve inline type", "life_cycle_status": "Active"},
  {"id": 152, "Part-Number": "ME-334645", "category": "Connector", "description": "Swivel joint rotary union", "life_cycle_status": "Active"},
  {"id": 153, "Part-Number": "TH-889712", "category": "Sensor", "description": "Laser distance sensor precision", "life_cycle_status": "Active"},
  {"id": 154, "Part-Number": "PR-556834", "category": "Pipe", "description": "Pipe union coupling threaded", "life_cycle_status": "Active"},
  {"id": 155, "Part-Number": "AE-112967", "category": "Filter", "description": "Cyclone separator pre-filter", "life_cycle_status": "Active"},
  {"id": 156, "Part-Number": "GL-667745", "category": "Pump", "description": "Split case pump horizontal mount", "life_cycle_status": "Active"},
  {"id": 157, "Part-Number": "ST-998823", "category": "Regulator", "description": "Loading station pressure regulator", "life_cycle_status": "Active"},
  {"id": 158, "Part-Number": "HY-445612", "category": "Seal", "description": "Bonded seal washer type", "life_cycle_status": "Active"},
  {"id": 159, "Part-Number": "EN-223789", "category": "Actuator", "description": "Pneumatic gripper parallel jaw", "life_cycle_status": "Active"},
  {"id": 160, "Part-Number": "OP-778634", "category": "Compressor", "description": "Roots blower positive displacement", "life_cycle_status": "Active"},
  {"id": 161, "Part-Number": "ME-112845", "category": "Valve", "description": "Piston valve control type", "life_cycle_status": "Active"},
  {"id": 162, "Part-Number": "GL-889534", "category": "Connector", "description": "Ground joint coupling glass", "life_cycle_status": "Active"},
  {"id": 163, "Part-Number": "TH-445723", "category": "Sensor", "description": "Oxygen sensor galvanic cell", "life_cycle_status": "Active"},
  {"id": 164, "Part-Number": "PR-998612", "category": "Pipe", "description": "Pipe nipple close threaded", "life_cycle_status": "Active"},
  {"id": 165, "Part-Number": "HY-667834", "category": "Filter", "description": "Bag filter housing multi-bag", "life_cycle_status": "Active"},
  {"id": 166, "Part-Number": "AE-334912", "category": "Pump", "description": "Booster pump multistage", "life_cycle_status": "Active"},
  {"id": 167, "Part-Number": "ST-556789", "category": "Regulator", "description": "Suction pressure regulator", "life_cycle_status": "Active"},
  {"id": 168, "Part-Number": "EN-112678", "category": "Seal", "description": "Chevron seal vee packing", "life_cycle_status": "Active"},
{"id": 169, "Part-Number": "OP-889612", "category": "Actuator", "description": "Belt-driven actuator linear motion", "life_cycle_status": "Active"},
  {"id": 170, "Part-Number": "GL-445734", "category": "Compressor", "description": "Sliding vane compressor rotary", "life_cycle_status": "Active"},
  {"id": 171, "Part-Number": "HY-223867", "category": "Valve", "description": "Isolation valve full port", "life_cycle_status": "Active"},
  {"id": 172, "Part-Number": "ME-778645", "category": "Connector", "description": "Weld neck flange connector", "life_cycle_status": "Active"},
  {"id": 173, "Part-Number": "TH-334956", "category": "Sensor", "description": "Capacitance level sensor", "life_cycle_status": "Active"},
  {"id": 174, "Part-Number": "PR-667812", "category": "Pipe", "description": "Pipe cross four-way fitting", "life_cycle_status": "Active"},
  {"id": 175, "Part-Number": "AE-998723", "category": "Filter", "description": "Activated carbon filter media", "life_cycle_status": "Active"},
  {"id": 176, "Part-Number": "GL-112867", "category": "Pump", "description": "Fire pump diesel driven", "life_cycle_status": "Active"},
  {"id": 177, "Part-Number": "ST-889645", "category": "Regulator", "description": "Evaporator pressure regulator", "life_cycle_status": "Active"},
  {"id": 178, "Part-Number": "HY-556712", "category": "Seal", "description": "Labrynth seal non-contacting", "life_cycle_status": "Active"},
  {"id": 179, "Part-Number": "EN-334823", "category": "Actuator", "description": "Screw-driven actuator high force", "life_cycle_status": "Active"},
  {"id": 180, "Part-Number": "OP-112956", "category": "Compressor", "description": "Mixed flow compressor hybrid", "life_cycle_status": "Active"},
  {"id": 181, "Part-Number": "ME-667923", "category": "Valve", "description": "Angle valve right angle", "life_cycle_status": "Active"},
  {"id": 182, "Part-Number": "GL-998734", "category": "Connector", "description": "Threaded union dielectric", "life_cycle_status": "Active"},
  {"id": 183, "Part-Number": "TH-223812", "category": "Sensor", "description": "Humidity sensor transmitter", "life_cycle_status": "Active"},
  {"id": 184, "Part-Number": "PR-889567", "category": "Pipe", "description": "Pipe plug solid type", "life_cycle_status": "Active"},
  {"id": 185, "Part-Number": "HY-112745", "category": "Filter", "description": "Depth filter cartridge wound", "life_cycle_status": "Active"},
  {"id": 186, "Part-Number": "AE-556823", "category": "Pump", "description": "Jet pump shallow well", "life_cycle_status": "Active"},
  {"id": 187, "Part-Number": "ST-334867", "category": "Regulator", "description": "Gas pressure regulator residential", "life_cycle_status": "Active"},
  {"id": 188, "Part-Number": "EN-998612", "category": "Seal", "description": "Spring energized seal PTFE", "life_cycle_status": "Active"},
  {"id": 189, "Part-Number": "OP-445789", "category": "Actuator", "description": "Cam-driven actuator rotary", "life_cycle_status": "Active"},
  {"id": 190, "Part-Number": "GL-778923", "category": "Compressor", "description": "Lobe compressor tri-lobe", "life_cycle_status": "Active"},
  {"id": 191, "Part-Number": "HY-334712", "category": "Valve", "description": "Three-way valve mixing type", "life_cycle_status": "Active"},
  {"id": 192, "Part-Number": "ME-889834", "category": "Connector", "description": "Slip-on flange raised face", "life_cycle_status": "Active"},
  {"id": 193, "Part-Number": "TH-667512", "category": "Sensor", "description": "Thermocouple sensor K-type", "life_cycle_status": "Active"},
  {"id": 194, "Part-Number": "PR-112834", "category": "Pipe", "description": "Pipe coupling grooved", "life_cycle_status": "Active"},
  {"id": 195, "Part-Number": "AE-889712", "category": "Filter", "description": "Spin-on filter canister type", "life_cycle_status": "Active"},
  {"id": 196, "Part-Number": "GL-334956", "category": "Pump", "description": "Reciprocating pump piston", "life_cycle_status": "Active"},
  {"id": 197, "Part-Number": "ST-223745", "category": "Regulator", "description": "Oxygen regulator medical grade", "life_cycle_status": "Active"},
  {"id": 198, "Part-Number": "HY-998678", "category": "Seal", "description": "Face seal metal gasket", "life_cycle_status": "Active"},
  {"id": 199, "Part-Number": "EN-556812", "category": "Actuator", "description": "Hydraulic cylinder telescopic", "life_cycle_status": "Active"},
  {"id": 200, "Part-Number": "OP-667834", "category": "Compressor", "description": "Helical screw compressor twin", "life_cycle_status": "Active"},
  {"id": 201, "Part-Number": "ME-445712", "category": "Valve", "description": "Pressure seal valve bonnet", "life_cycle_status": "Active"},
  {"id": 202, "Part-Number": "GL-112923", "category": "Connector", "description": "Socket weld coupling forged", "life_cycle_status": "Active"},
  {"id": 203, "Part-Number": "TH-778834", "category": "Sensor", "description": "RTD sensor Pt100 type", "life_cycle_status": "Active"},
  {"id": 204, "Part-Number": "PR-334867", "category": "Pipe", "description": "Reducing tee unequal", "life_cycle_status": "Active"},
  {"id": 205, "Part-Number": "HY-889623", "category": "Filter", "description": "Self-cleaning filter screen", "life_cycle_status": "Active"},
  {"id": 206, "Part-Number": "AE-667745", "category": "Pump", "description": "Axial flow pump propeller", "life_cycle_status": "Active"},
  {"id": 207, "Part-Number": "ST-998567", "category": "Regulator", "description": "Air line pressure regulator", "life_cycle_status": "Active"},
  {"id": 208, "Part-Number": "EN-223956", "category": "Seal", "description": "U-cup seal single acting", "life_cycle_status": "Active"},
  {"id": 209, "Part-Number": "OP-556734", "category": "Actuator", "description": "Rack and pinion actuator pneumatic", "life_cycle_status": "Active"},
  {"id": 210, "Part-Number": "GL-889812", "category": "Compressor", "description": "Isothermal compressor cooled", "life_cycle_status": "Active"},
  {"id": 211, "Part-Number": "HY-112867", "category": "Valve", "description": "Flush bottom valve tank", "life_cycle_status": "Active"},
  {"id": 212, "Part-Number": "ME-334789", "category": "Connector", "description": "Lap joint flange loose", "life_cycle_status": "Active"},
  {"id": 213, "Part-Number": "TH-998612", "category": "Sensor", "description": "Strain gauge load cell", "life_cycle_status": "Active"},
  {"id": 214, "Part-Number": "PR-778945", "category": "Pipe", "description": "Concentric reducer fitting", "life_cycle_status": "Active"},
  {"id": 215, "Part-Number": "HY-445823", "category": "Filter", "description": "Inline filter strainer", "life_cycle_status": "Active"},
  {"id": 216, "Part-Number": "AE-112834", "category": "Pump", "description": "Screw pump twin helical", "life_cycle_status": "Active"},
  {"id": 217, "Part-Number": "ST-667812", "category": "Regulator", "description": "Cylinder regulator adjustable", "life_cycle_status": "Active"},
  {"id": 218, "Part-Number": "EN-889534", "category": "Seal", "description": "T-seal wiperring backup", "life_cycle_status": "Active"},
  {"id": 219, "Part-Number": "OP-223867", "category": "Actuator", "description": "Direct drive actuator servo", "life_cycle_status": "Active"},
  {"id": 220, "Part-Number": "GL-556912", "category": "Compressor", "description": "Oil-flooded compressor rotary", "life_cycle_status": "Active"},
  {"id": 221, "Part-Number": "HY-998734", "category": "Valve", "description": "Zero leakage valve sealed", "life_cycle_status": "Active"},
  {"id": 222, "Part-Number": "ME-112756", "category": "Connector", "description": "Blind flange solid", "life_cycle_status": "Active"},
  {"id": 223, "Part-Number": "TH-556834", "category": "Sensor", "description": "Pressure switch mechanical", "life_cycle_status": "Active"},
  {"id": 224, "Part-Number": "PR-445712", "category": "Pipe", "description": "Eccentric reducer offset", "life_cycle_status": "Active"},
  {"id": 225, "Part-Number": "HY-667923", "category": "Filter", "description": "Magnetic filter inline", "life_cycle_status": "Active"},
  {"id": 226, "Part-Number": "AE-998834", "category": "Pump", "description": "Vortex pump impeller free", "life_cycle_status": "Active"},
  {"id": 227, "Part-Number": "ST-334712", "category": "Regulator", "description": "Pilot operated regulator", "life_cycle_status": "Active"},
  {"id": 228, "Part-Number": "EN-778645", "category": "Seal", "description": "Wiper seal dust exclusion", "life_cycle_status": "Active"},
  {"id": 229, "Part-Number": "OP-889745", "category": "Actuator", "description": "Voice coil actuator linear", "life_cycle_status": "Active"},
  {"id": 230, "Part-Number": "GL-223834", "category": "Compressor", "description": "Portable compressor wheeled", "life_cycle_status": "Active"},
  {"id": 231, "Part-Number": "HY-556789", "category": "Valve", "description": "Cryogenic valve extended bonnet", "life_cycle_status": "Active"},
  {"id": 232, "Part-Number": "ME-998612", "category": "Connector", "description": "Orifice flange weld neck", "life_cycle_status": "Active"},
  {"id": 233, "Part-Number": "TH-112867", "category": "Sensor", "description": "Photoelectric sensor reflective", "life_cycle_status": "Active"},
  {"id": 234, "Part-Number": "PR-889734", "category": "Pipe", "description": "Street elbow threaded", "life_cycle_status": "Active"},
  {"id": 235, "Part-Number": "HY-334912", "category": "Filter", "description": "Coalescing filter separator", "life_cycle_status": "Active"},
  {"id": 236, "Part-Number": "AE-445867", "category": "Pump", "description": "Slurry pump abrasion resistant", "life_cycle_status": "Active"},
  {"id": 237, "Part-Number": "ST-778623", "category": "Regulator", "description": "Tank blanketing regulator", "life_cycle_status": "Active"},
  {"id": 238, "Part-Number": "EN-112945", "category": "Seal", "description": "Piston seal double acting", "life_cycle_status": "Active"},
  {"id": 239, "Part-Number": "OP-334812", "category": "Actuator", "description": "Diaphragm actuator flexible", "life_cycle_status": "Active"},
  {"id": 240, "Part-Number": "GL-998867", "category": "Compressor", "description": "Hermetic compressor sealed", "life_cycle_status": "Active"},
  {"id": 241, "Part-Number": "HY-667812", "category": "Valve", "description": "Trunnion mounted valve ball", "life_cycle_status": "Active"},
  {"id": 242, "Part-Number": "ME-223734", "category": "Connector", "description": "Expansion joint bellows", "life_cycle_status": "Active"},
  {"id": 243, "Part-Number": "TH-889623", "category": "Sensor", "description": "Magnetic reed switch sensor", "life_cycle_status": "Active"},
  {"id": 244, "Part-Number": "PR-556912", "category": "Pipe", "description": "Swage nipple reducing", "life_cycle_status": "Active"},
  {"id": 245, "Part-Number": "HY-112734", "category": "Filter", "description": "Gas filter separator element", "life_cycle_status": "Active"},
  {"id": 246, "Part-Number": "AE-778923", "category": "Pump", "description": "Barrel pump drum transfer", "life_cycle_status": "Active"},
  {"id": 247, "Part-Number": "ST-445689", "category": "Regulator", "description": "Breathing air regulator", "life_cycle_status": "Active"},
  {"id": 248, "Part-Number": "EN-334867", "category": "Seal", "description": "Buffer seal intermediate", "life_cycle_status": "Active"},
  {"id": 249, "Part-Number": "OP-998723", "category": "Actuator", "description": "Rotary vane actuator pneumatic", "life_cycle_status": "Active"},
  {"id": 250, "Part-Number": "GL-667834", "category": "Compressor", "description": "Tandem compressor dual", "life_cycle_status": "Active"},
  {"id": 251, "Part-Number": "HY-889712", "category": "Valve", "description": "Mixing valve thermostatic", "life_cycle_status": "Active"},
  {"id": 252, "Part-Number": "ME-556823", "category": "Connector", "description": "Reducing flange adapter", "life_cycle_status": "Active"},
  {"id": 253, "Part-Number": "TH-334812", "category": "Sensor", "description": "Hall effect sensor magnetic", "life_cycle_status": "Active"},
  {"id": 254, "Part-Number": "PR-112867", "category": "Pipe", "description": "Bullhead tee branch equal", "life_cycle_status": "Active"},
  {"id": 255, "Part-Number": "HY-998812", "category": "Filter", "description": "Vacuum filter separator", "life_cycle_status": "Active"},
  {"id": 256, "Part-Number": "AE-223867", "category": "Pump", "description": "Metering pump dosing precision", "life_cycle_status": "Active"},
  {"id": 257, "Part-Number": "ST-889734", "category": "Regulator", "description": "Diaphragm regulator sensitive", "life_cycle_status": "Active"},
  {"id": 258, "Part-Number": "EN-667912", "category": "Seal", "description": "Bonded piston seal composite", "life_cycle_status": "Active"},
  {"id": 259, "Part-Number": "OP-778912", "category": "Actuator", "description": "Bellows actuator sealed", "life_cycle_status": "Active"},
  {"id": 260, "Part-Number": "GL-112834", "category": "Compressor", "description": "Duplex compressor backup", "life_cycle_status": "Active"},
  {"id": 261, "Part-Number": "HY-334867", "category": "Valve", "description": "Multiport valve selector", "life_cycle_status": "Active"},
  {"id": 262, "Part-Number": "ME-889712", "category": "Connector", "description": "Long weld neck flange", "life_cycle_status": "Active"},
  {"id": 263, "Part-Number": "TH-667834", "category": "Sensor", "description": "Fiber optic sensor amplifier", "life_cycle_status": "Active"},
  {"id": 264, "Part-Number": "PR-998756", "category": "Pipe", "description": "Lateral tee side outlet", "life_cycle_status": "Active"},
  {"id": 265, "Part-Number": "HY-556834", "category": "Filter", "description": "Compressed air filter coalescer", "life_cycle_status": "Active"},
  {"id": 266, "Part-Number": "AE-334923", "category": "Pump", "description": "Trash pump solids handling", "life_cycle_status": "Active"},
  {"id": 267, "Part-Number": "ST-112789", "category": "Regulator", "description": "Manifold pressure regulator", "life_cycle_status": "Active"},
  {"id": 268, "Part-Number": "EN-445912", "category": "Seal", "description": "Gasket spiral wound", "life_cycle_status": "Active"},
  {"id": 269, "Part-Number": "OP-667923", "category": "Actuator", "description": "Failsafe actuator spring return", "life_cycle_status": "Active"},
  {"id": 270, "Part-Number": "GL-889867", "category": "Compressor", "description": "Booster compressor high ratio", "life_cycle_status": "Active"},
  {"id": 271, "Part-Number": "HY-223912", "category": "Valve", "description": "Vacuum breaker valve atmospheric", "life_cycle_status": "Active"},
  {"id": 272, "Part-Number": "ME-667834", "category": "Connector", "description": "Spectacle blind figure eight", "life_cycle_status": "Active"},
  {"id": 273, "Part-Number": "TH-998712", "category": "Sensor", "description": "Capacitive proximity sensor", "life_cycle_status": "Active"},
  {"id": 274, "Part-Number": "PR-334923", "category": "Pipe", "description": "Reducing coupling threaded", "life_cycle_status": "Active"},
  {"id": 275, "Part-Number": "HY-778834", "category": "Filter", "description": "Breather filter vent", "life_cycle_status": "Active"},
  {"id": 276, "Part-Number": "AE-889867", "category": "Pump", "description": "Hydraulic hand pump manual", "life_cycle_status": "Active"},
  {"id": 277, "Part-Number": "ST-556912", "category": "Regulator", "description": "Compound pressure regulator", "life_cycle_status": "Active"},
  {"id": 278, "Part-Number": "EN-998734", "category": "Seal", "description": "Inflatable seal pneumatic", "life_cycle_status": "Active"},
  {"id": 279, "Part-Number": "OP-112834", "category": "Actuator", "description": "Stepping motor actuator indexed", "life_cycle_status": "Active"},
  {"id": 280, "Part-Number": "GL-445912", "category": "Compressor", "description": "Package compressor skid mounted", "life_cycle_status": "Active"},
  {"id": 281, "Part-Number": "HY-667912", "category": "Valve", "description": "Foot valve check type", "life_cycle_status": "Active"},
  {"id": 282, "Part-Number": "ME-112834", "category": "Connector", "description": "Paddle blind spade", "life_cycle_status": "Active"},
  {"id": 283, "Part-Number": "TH-445867", "category": "Sensor", "description": "Ultrasonic sensor through-beam", "life_cycle_status": "Active"},
  {"id": 284, "Part-Number": "PR-667923", "category": "Pipe", "description": "Weldolet branch fitting", "life_cycle_status": "Active"},
  {"id": 285, "Part-Number": "HY-223834", "category": "Filter", "description": "Mist eliminator coalescer", "life_cycle_status": "Active"},
  {"id": 286, "Part-Number": "AE-556912", "category": "Pump", "description": "Sump pump submersible", "life_cycle_status": "Active"},
  {"id": 287, "Part-Number": "ST-667923", "category": "Regulator", "description": "Line pressure regulator", "life_cycle_status": "Active"},
  {"id": 288, "Part-Number": "EN-112867", "category": "Seal", "description": "Compression packing braided", "life_cycle_status": "Active"},
  {"id": 289, "Part-Number": "OP-889812", "category": "Actuator", "description": "Modulating actuator proportional", "life_cycle_status": "Active"},
  {"id": 290, "Part-Number": "GL-334867", "category": "Compressor", "description": "Silent compressor low noise", "life_cycle_status": "Active"},
  {"id": 291, "Part-Number": "HY-112923", "category": "Valve", "description": "Back pressure valve spring", "life_cycle_status": "Active"},
  {"id": 292, "Part-Number": "ME-998867", "category": "Connector", "description": "Victaulic coupling grooved", "life_cycle_status": "Active"},
  {"id": 293, "Part-Number": "TH-223867", "category": "Sensor", "description": "Color mark sensor RGB", "life_cycle_status": "Active"},
  {"id": 294, "Part-Number": "PR-889812", "category": "Pipe", "description": "Sockolet socket weld", "life_cycle_status": "Active"},
  {"id": 295, "Part-Number": "HY-445867", "category": "Filter", "description": "Diesel particulate filter", "life_cycle_status": "Active"},
  {"id": 296, "Part-Number": "AE-667923", "category": "Pump", "description": "Bilge pump marine type", "life_cycle_status": "Active"},
  {"id": 297, "Part-Number": "ST-112912", "category": "Regulator", "description": "Changeover pressure regulator", "life_cycle_status": "Active"},
  {"id": 298, "Part-Number": "EN-556923", "category": "Seal", "description": "Molded seal elastomer", "life_cycle_status": "Active"},
  {"id": 299, "Part-Number": "OP-334867", "category": "Actuator", "description": "Manual override actuator", "life_cycle_status": "Active"},
  {"id": 300, "Part-Number": "GL-778867", "category": "Compressor", "description": "Medical air compressor oilless", "life_cycle_status": "Active"},
  {"id": 301, "Part-Number": "HY-998867", "category": "Valve", "description": "Automated control valve motorized", "life_cycle_status": "Active"},
  {"id": 302, "Part-Number": "ME-445867", "category": "Connector", "description": "Threadolet threaded branch", "life_cycle_status": "Active"},
  {"id": 303, "Part-Number": "TH-889812", "category": "Sensor", "description": "Differential pressure sensor", "life_cycle_status": "Active"},
  {"id": 304, "Part-Number": "PR-223867", "category": "Pipe", "description": "Sweep elbow long radius", "life_cycle_status": "Active"},
  {"id": 305, "Part-Number": "HY-889867", "category": "Filter", "description": "Water separator filter drain", "life_cycle_status": "Active"},
  {"id": 306, "Part-Number": "AE-112923", "category": "Pump", "description": "Chemical injection pump", "life_cycle_status": "Active"},
  {"id": 307, "Part-Number": "ST-334867", "category": "Regulator", "description": "Precision pressure regulator", "life_cycle_status": "Active"},
  {"id": 308, "Part-Number": "EN-889812", "category": "Seal", "description": "Graphite packing flexible", "life_cycle_status": "Active"},
  {"id": 309, "Part-Number": "OP-223912", "category": "Actuator", "description": "Quarter turn actuator 90 degree", "life_cycle_status": "Active"},
  {"id": 310, "Part-Number": "GL-112923", "category": "Compressor", "description": "Truck mounted compressor mobile", "life_cycle_status": "Active"},
  {"id": 311, "Part-Number": "HY-556867", "category": "Valve", "description": "Solenoid valve direct acting", "life_cycle_status": "Active"},
  {"id": 312, "Part-Number": "ME-334912", "category": "Connector", "description": "Elbolet elbow outlet", "life_cycle_status": "Active"},
  {"id": 313, "Part-Number": "TH-667912", "category": "Sensor", "description": "Barcode scanner laser", "life_cycle_status": "Active"},
  {"id": 314, "Part-Number": "PR-445867", "category": "Pipe", "description": "Return bend 180 degree", "life_cycle_status": "Active"},
  {"id": 315, "Part-Number": "HY-112867", "category": "Filter", "description": "Oil mist collector separator", "life_cycle_status": "Active"},
  {"id": 316, "Part-Number": "AE-998912", "category": "Pump", "description": "Drum pump electric motor", "life_cycle_status": "Active"},
  {"id": 317, "Part-Number": "ST-889867", "category": "Regulator", "description": "Vacuum regulator control", "life_cycle_status": "Active"},
  {"id": 318, "Part-Number": "EN-223867", "category": "Seal", "description": "Gland packing asbestos free", "life_cycle_status": "Active"},
  {"id": 319, "Part-Number": "OP-778867", "category": "Actuator", "description": "Multi-turn actuator geared", "life_cycle_status": "Active"},
  {"id": 320, "Part-Number": "GL-667912", "category": "Compressor", "description": "Laboratory compressor quiet", "life_cycle_status": "Active"},
  {"id": 321, "Part-Number": "HY-334923", "category": "Valve", "description": "Dome loaded valve pilot", "life_cycle_status": "Active"},
  {"id": 322, "Part-Number": "ME-889912", "category": "Connector", "description": "Latrolet lateral outlet", "life_cycle_status": "Active"},
  {"id": 323, "Part-Number": "TH-112923", "category": "Sensor", "description": "Vision sensor camera based", "life_cycle_status": "Active"},
  {"id": 324, "Part-Number": "PR-998867", "category": "Pipe", "description": "Mitered elbow fabricated", "life_cycle_status": "Active"},
  {"id": 325, "Part-Number": "HY-667867", "category": "Filter", "description": "Pulse jet filter baghouse", "life_cycle_status": "Active"},
  {"id": 326, "Part-Number": "AE-334867", "category": "Pump", "description": "Coolant pump circulation", "life_cycle_status": "Active"},
  {"id": 327, "Part-Number": "ST-223912", "category": "Regulator", "description": "Heated pressure regulator", "life_cycle_status": "Active"},
  {"id": 328, "Part-Number": "EN-778912", "category": "Seal", "description": "Double mechanical seal tandem", "life_cycle_status": "Active"},
  {"id": 329, "Part-Number": "OP-112923", "category": "Actuator", "description": "Explosion proof actuator ATEX", "life_cycle_status": "Active"},
  {"id": 330, "Part-Number": "GL-998912", "category": "Compressor", "description": "Paintball compressor high pressure", "life_cycle_status": "Active"},
  {"id": 331, "Part-Number": "HY-889912", "category": "Valve", "description": "Jacketed valve heated", "life_cycle_status": "Active"},
  {"id": 332, "Part-Number": "ME-223867", "category": "Connector", "description": "Sweepolet swept outlet", "life_cycle_status": "Active"},
  {"id": 333, "Part-Number": "TH-556912", "category": "Sensor", "description": "Gas detector combustible", "life_cycle_status": "Active"},
  {"id": 334, "Part-Number": "PR-112923", "category": "Pipe", "description": "Reducing elbow concentric", "life_cycle_status": "Active"},
  {"id": 335, "Part-Number": "HY-334867", "category": "Filter", "description": "Pleated cartridge filter polyester", "life_cycle_status": "Active"},
  {"id": 336, "Part-Number": "AE-889912", "category": "Pump", "description": "Lobe pump sanitary", "life_cycle_status": "Active"},
  {"id": 337, "Part-Number": "ST-998912", "category": "Regulator", "description": "Low pressure regulator gas", "life_cycle_status": "Active"},
  {"id": 338, "Part-Number": "EN-112923", "category": "Seal", "description": "Cartridge seal pusher type", "life_cycle_status": "Active"},
  {"id": 339, "Part-Number": "OP-667912", "category": "Actuator", "description": "Piston actuator high torque", "life_cycle_status": "Active"},
  {"id": 340, "Part-Number": "GL-556923", "category": "Compressor", "description": "Refrigeration compressor scroll type", "life_cycle_status": "Active"},
  {"id": 341, "Part-Number": "HY-112934", "category": "Valve", "description": "Lined valve PTFE coated", "life_cycle_status": "Active"},
  {"id": 342, "Part-Number": "ME-778912", "category": "Connector", "description": "Nipolet nipple outlet", "life_cycle_status": "Active"},
  {"id": 343, "Part-Number": "TH-334923", "category": "Sensor", "description": "Smoke detector ionization", "life_cycle_status": "Active"},
  {"id": 344, "Part-Number": "PR-889912", "category": "Pipe", "description": "Cross over pipe manifold", "life_cycle_status": "Active"},
  {"id": 345, "Part-Number": "HY-998923", "category": "Filter", "description": "Reverse osmosis membrane filter", "life_cycle_status": "Active"},
  {"id": 346, "Part-Number": "AE-223912", "category": "Pump", "description": "Pool pump circulating", "life_cycle_status": "Active"},
  {"id": 347, "Part-Number": "ST-667912", "category": "Regulator", "description": "Dual stage regulator cascade", "life_cycle_status": "Active"},
  {"id": 348, "Part-Number": "EN-667923", "category": "Seal", "description": "Split mechanical seal retrofit", "life_cycle_status": "Active"},
  {"id": 349, "Part-Number": "OP-998912", "category": "Actuator", "description": "Scotch yoke actuator high torque", "life_cycle_status": "Active"},
  {"id": 350, "Part-Number": "GL-889923", "category": "Compressor", "description": "Air dryer compressor integrated", "life_cycle_status": "Active"},
  {"id": 351, "Part-Number": "HY-223923", "category": "Valve", "description": "Lined plug valve rubber", "life_cycle_status": "Active"},
  {"id": 352, "Part-Number": "ME-556912", "category": "Connector", "description": "Coupling half API specification", "life_cycle_status": "Active"},
  {"id": 353, "Part-Number": "TH-778923", "category": "Sensor", "description": "Flame detector UV/IR", "life_cycle_status": "Active"},
  {"id": 354, "Part-Number": "PR-334912", "category": "Pipe", "description": "Stub end lap joint", "life_cycle_status": "Active"},
  {"id": 355, "Part-Number": "HY-556923", "category": "Filter", "description": "HEPA filter high efficiency", "life_cycle_status": "Active"},
  {"id": 356, "Part-Number": "AE-778912", "category": "Pump", "description": "Well pump deep submersible", "life_cycle_status": "Active"},
  {"id": 357, "Part-Number": "ST-112923", "category": "Regulator", "description": "Vent pressure regulator atmospheric", "life_cycle_status": "Active"},
  {"id": 358, "Part-Number": "EN-998912", "category": "Seal", "description": "Floating seal self-aligning", "life_cycle_status": "Active"},
  {"id": 359, "Part-Number": "OP-556923", "category": "Actuator", "description": "Part-turn actuator 120 degree", "life_cycle_status": "Active"},
  {"id": 360, "Part-Number": "GL-223923", "category": "Compressor", "description": "Breathing air compressor CGA", "life_cycle_status": "Active"},
  {"id": 361, "Part-Number": "HY-778912", "category": "Valve", "description": "Slab gate valve expanding", "life_cycle_status": "Active"},
  {"id": 362, "Part-Number": "ME-112923", "category": "Connector", "description": "Reducing insert bushing", "life_cycle_status": "Active"},
  {"id": 363, "Part-Number": "TH-998923", "category": "Sensor", "description": "Torque sensor strain gauge", "life_cycle_status": "Active"},
  {"id": 364, "Part-Number": "PR-556923", "category": "Pipe", "description": "Pipe shoe support saddle", "life_cycle_status": "Active"},
  {"id": 365, "Part-Number": "HY-889923", "category": "Filter", "description": "Ultrafiltration membrane module", "life_cycle_status": "Active"},
  {"id": 366, "Part-Number": "AE-112967", "category": "Pump", "description": "Transfer pump portable", "life_cycle_status": "Active"},
  {"id": 367, "Part-Number": "ST-445923", "category": "Regulator", "description": "Bellows sealed regulator", "life_cycle_status": "Active"},
  {"id": 368, "Part-Number": "EN-334912", "category": "Seal", "description": "Stationary seal face", "life_cycle_status": "Active"},
  {"id": 369, "Part-Number": "OP-889923", "category": "Actuator", "description": "Pneumatic rotary actuator vane", "life_cycle_status": "Active"},
  {"id": 370, "Part-Number": "GL-778912", "category": "Compressor", "description": "Natural gas compressor pipeline", "life_cycle_status": "Active"},
  {"id": 371, "Part-Number": "HY-667923", "category": "Valve", "description": "Knife gate valve slurry", "life_cycle_status": "Active"},
  {"id": 372, "Part-Number": "ME-889923", "category": "Connector", "description": "Pipe adapter flanged", "life_cycle_status": "Active"},
  {"id": 373, "Part-Number": "TH-667923", "category": "Sensor", "description": "Acceleration sensor MEMS", "life_cycle_status": "Active"},
  {"id": 374, "Part-Number": "PR-778912", "category": "Pipe", "description": "Elbow street reducing", "life_cycle_status": "Active"},
  {"id": 375, "Part-Number": "HY-112923", "category": "Filter", "description": "Microfiltration cartridge ceramic", "life_cycle_status": "Active"},
  {"id": 376, "Part-Number": "AE-667912", "category": "Pump", "description": "Condensate pump HVAC", "life_cycle_status": "Active"},
  {"id": 377, "Part-Number": "ST-778912", "category": "Regulator", "description": "Cryo regulator low temperature", "life_cycle_status": "Active"},
  {"id": 378, "Part-Number": "EN-445923", "category": "Seal", "description": "Rotating seal face carbon", "life_cycle_status": "Active"},
  {"id": 379, "Part-Number": "OP-334923", "category": "Actuator", "description": "Fail-freeze actuator lock", "life_cycle_status": "Active"},
  {"id": 380, "Part-Number": "GL-667923", "category": "Compressor", "description": "Nitrogen generator compressor", "life_cycle_status": "Active"},
  {"id": 381, "Part-Number": "HY-556912", "category": "Valve", "description": "Wafer check valve dual plate", "life_cycle_status": "Active"},
  {"id": 382, "Part-Number": "ME-667912", "category": "Connector", "description": "Reducing tee branch outlet", "life_cycle_status": "Active"},
  {"id": 383, "Part-Number": "TH-889923", "category": "Sensor", "description": "Encoder rotary absolute", "life_cycle_status": "Active"},
  {"id": 384, "Part-Number": "PR-667912", "category": "Pipe", "description": "Coupling compression type", "life_cycle_status": "Active"},
  {"id": 385, "Part-Number": "HY-334923", "category": "Filter", "description": "Nanofiltration membrane system", "life_cycle_status": "Active"},
  {"id": 386, "Part-Number": "AE-556923", "category": "Pump", "description": "Effluent pump sewage", "life_cycle_status": "Active"},
  {"id": 387, "Part-Number": "ST-889923", "category": "Regulator", "description": "Steam pressure reducing station", "life_cycle_status": "Active"},
  {"id": 388, "Part-Number": "EN-556912", "category": "Seal", "description": "Bellows seal metal", "life_cycle_status": "Active"},
  {"id": 389, "Part-Number": "OP-445923", "category": "Actuator", "description": "Linear slide actuator precision", "life_cycle_status": "Active"},
  {"id": 390, "Part-Number": "GL-112967", "category": "Compressor", "description": "Vapor recovery compressor", "life_cycle_status": "Active"},
  {"id": 391, "Part-Number": "HY-445923", "category": "Valve", "description": "Eccentric plug valve resilient", "life_cycle_status": "Active"},
  {"id": 392, "Part-Number": "ME-998923", "category": "Connector", "description": "Reducing cross unequal", "life_cycle_status": "Active"},
  {"id": 393, "Part-Number": "TH-112967", "category": "Sensor", "description": "Inclinometer tilt sensor", "life_cycle_status": "Active"},
  {"id": 394, "Part-Number": "PR-112967", "category": "Pipe", "description": "Barrel nipple long", "life_cycle_status": "Active"},
  {"id": 395, "Part-Number": "HY-223967", "category": "Filter", "description": "Sand filter media tank", "life_cycle_status": "Active"},
  {"id": 396, "Part-Number": "AE-445923", "category": "Pump", "description": "Grinder pump sewage", "life_cycle_status": "Active"},
  {"id": 397, "Part-Number": "ST-334923", "category": "Regulator", "description": "Instrument air regulator clean", "life_cycle_status": "Active"},
  {"id": 398, "Part-Number": "EN-889923", "category": "Seal", "description": "Dry gas seal non-contacting", "life_cycle_status": "Active"},
  {"id": 399, "Part-Number": "OP-667923", "category": "Actuator", "description": "Pneumatic gripping actuator", "life_cycle_status": "Active"},
  {"id": 400, "Part-Number": "GL-998923", "category": "Compressor", "description": "Hydrogen compressor diaphragm", "life_cycle_status": "Active"},
  {"id": 401, "Part-Number": "HY-334967", "category": "Valve", "description": "Double block bleed valve", "life_cycle_status": "Active"},
  {"id": 402, "Part-Number": "ME-223923", "category": "Connector", "description": "Reducing lateral branch", "life_cycle_status": "Active"},
  {"id": 403, "Part-Number": "TH-445923", "category": "Sensor", "description": "Gyroscope sensor angular", "life_cycle_status": "Active"},
  {"id": 404, "Part-Number": "PR-889923", "category": "Pipe", "description": "Hex nipple double ended", "life_cycle_status": "Active"},
  {"id": 405, "Part-Number": "HY-778923", "category": "Filter", "description": "Gravity filter clarifier", "life_cycle_status": "Active"},
  {"id": 406, "Part-Number": "AE-334967", "category": "Pump", "description": "Brine pump corrosion resistant", "life_cycle_status": "Active"},
  {"id": 407, "Part-Number": "ST-556923", "category": "Regulator", "description": "Panel mounted regulator gauge", "life_cycle_status": "Active"},
  {"id": 408, "Part-Number": "EN-112967", "category": "Seal", "description": "Slurry seal abrasion resistant", "life_cycle_status": "Active"},
  {"id": 409, "Part-Number": "OP-556967", "category": "Actuator", "description": "Fail-open actuator spring", "life_cycle_status": "Active"},
  {"id": 410, "Part-Number": "GL-334923", "category": "Compressor", "description": "CO2 compressor transcritical", "life_cycle_status": "Active"},
  {"id": 411, "Part-Number": "HY-889967", "category": "Valve", "description": "Lined butterfly valve EPDM", "life_cycle_status": "Active"},
  {"id": 412, "Part-Number": "ME-445923", "category": "Connector", "description": "Branch outlet tee reducing", "life_cycle_status": "Active"},
  {"id": 413, "Part-Number": "TH-556967", "category": "Sensor", "description": "Linear variable displacement transducer", "life_cycle_status": "Active"},
  {"id": 414, "Part-Number": "PR-223923", "category": "Pipe", "description": "Shoulder nipple welding", "life_cycle_status": "Active"},
  {"id": 415, "Part-Number": "HY-667967", "category": "Filter", "description": "Pressure filter vessel", "life_cycle_status": "Active"},
  {"id": 416, "Part-Number": "AE-889923", "category": "Pump", "description": "Circulation pump heating", "life_cycle_status": "Active"},
  {"id": 417, "Part-Number": "ST-112967", "category": "Regulator", "description": "Electronic pressure regulator", "life_cycle_status": "Active"},
  {"id": 418, "Part-Number": "EN-667967", "category": "Seal", "description": "Hygienic seal sanitary", "life_cycle_status": "Active"},
  {"id": 419, "Part-Number": "OP-889967", "category": "Actuator", "description": "Fail-closed actuator spring", "life_cycle_status": "Active"},
  {"id": 420, "Part-Number": "GL-556967", "category": "Compressor", "description": "Ammonia compressor refrigeration", "life_cycle_status": "Active"},
  {"id": 421, "Part-Number": "HY-998967", "category": "Valve", "description": "Triple offset butterfly valve", "life_cycle_status": "Active"},
  {"id": 422, "Part-Number": "ME-778923", "category": "Connector", "description": "Instrumentation fitting double ferrule", "life_cycle_status": "Active"},
  {"id": 423, "Part-Number": "TH-334967", "category": "Sensor", "description": "Force sensor piezoelectric", "life_cycle_status": "Active"},
  {"id": 424, "Part-Number": "PR-778923", "category": "Pipe", "description": "Reducing bushing hex head", "life_cycle_status": "Active"},
  {"id": 425, "Part-Number": "HY-112967", "category": "Filter", "description": "Catalytic filter oxidation", "life_cycle_status": "Active"},
  {"id": 426, "Part-Number": "AE-112945", "category": "Pump", "description": "Chopper pump solids handling", "life_cycle_status": "Active"},
  {"id": 427, "Part-Number": "ST-667967", "category": "Regulator", "description": "Zone pressure regulator manifold", "life_cycle_status": "Active"},
  {"id": 428, "Part-Number": "EN-223923", "category": "Seal", "description": "FDA approved seal food grade", "life_cycle_status": "Active"},
  {"id": 429, "Part-Number": "OP-223967", "category": "Actuator", "description": "Double acting cylinder piston", "life_cycle_status": "Active"},
  {"id": 430, "Part-Number": "GL-445967", "category": "Compressor", "description": "LNG compressor cryogenic", "life_cycle_status": "Active"},
  {"id": 431, "Part-Number": "HY-556967", "category": "Valve", "description": "Pressure balance valve lubricated", "life_cycle_status": "Active"},
  {"id": 432, "Part-Number": "ME-334967", "category": "Connector", "description": "Union connector dielectric insulated", "life_cycle_status": "Active"},
  {"id": 433, "Part-Number": "TH-778967", "category": "Sensor", "description": "Pyrometer infrared temperature", "life_cycle_status": "Active"},
  {"id": 434, "Part-Number": "PR-998923", "category": "Pipe", "description": "Bend pipe hot formed", "life_cycle_status": "Active"},
  {"id": 435, "Part-Number": "HY-998934", "category": "Filter", "description": "Ion exchange resin filter", "life_cycle_status": "Active"},
  {"id": 436, "Part-Number": "AE-998967", "category": "Pump", "description": "Vertical turbine pump lineshaft", "life_cycle_status": "Active"},
  {"id": 437, "Part-Number": "ST-223967", "category": "Regulator", "description": "High flow capacity regulator", "life_cycle_status": "Active"},
  {"id": 438, "Part-Number": "EN-778923", "category": "Seal", "description": "High pressure seal energized", "life_cycle_status": "Active"},
  {"id": 439, "Part-Number": "OP-112967", "category": "Actuator", "description": "Single acting cylinder spring return", "life_cycle_status": "Active"},
  {"id": 440, "Part-Number": "GL-889934", "category": "Compressor", "description": "Process gas compressor reciprocating", "life_cycle_status": "Active"},
  {"id": 441, "Part-Number": "HY-445967", "category": "Valve", "description": "Sleeved plug valve lubricated", "life_cycle_status": "Active"},
  {"id": 442, "Part-Number": "ME-889967", "category": "Connector", "description": "Hydraulic adapter straight", "life_cycle_status": "Active"},
  {"id": 443, "Part-Number": "TH-223934", "category": "Sensor", "description": "Eddy current sensor displacement", "life_cycle_status": "Active"},
  {"id": 444, "Part-Number": "PR-334967", "category": "Pipe", "description": "Tee outlet reducing on run", "life_cycle_status": "Active"},
  {"id": 445, "Part-Number": "HY-334934", "category": "Filter", "description": "Electrocoagulation filter system", "life_cycle_status": "Active"},
  {"id": 446, "Part-Number": "AE-223967", "category": "Pump", "description": "Split case pump vertical", "life_cycle_status": "Active"},
  {"id": 447, "Part-Number": "ST-889934", "category": "Regulator", "description": "Ultra high purity regulator", "life_cycle_status": "Active"},
  {"id": 448, "Part-Number": "EN-334967", "category": "Seal", "description": "Balanced seal pressure compensated", "life_cycle_status": "Active"},
  {"id": 449, "Part-Number": "OP-778923", "category": "Actuator", "description": "Rodless cylinder magnetic coupling", "life_cycle_status": "Active"},
  {"id": 450, "Part-Number": "GL-223967", "category": "Compressor", "description": "Chlorine compressor dry type", "life_cycle_status": "Active"},
  {"id": 451, "Part-Number": "HY-223934", "category": "Valve", "description": "Bellows seal globe valve", "life_cycle_status": "Active"},
  {"id": 452, "Part-Number": "ME-112967", "category": "Connector", "description": "Hydraulic adapter elbow", "life_cycle_status": "Active"},
  {"id": 453, "Part-Number": "TH-889967", "category": "Sensor", "description": "Magnetostrictive position sensor", "life_cycle_status": "Active"},
  {"id": 454, "Part-Number": "PR-556967", "category": "Pipe", "description": "Cap butt weld end", "life_cycle_status": "Active"},
  {"id": 455, "Part-Number": "HY-556934", "category": "Filter", "description": "Electrostatic precipitator filter", "life_cycle_status": "Active"},
  {"id": 456, "Part-Number": "AE-778967", "category": "Pump", "description": "Axially split case pump multistage", "life_cycle_status": "Active"},
  {"id": 457, "Part-Number": "ST-998967", "category": "Regulator", "description": "Corrosive gas regulator specialty", "life_cycle_status": "Active"},
  {"id": 458, "Part-Number": "EN-889967", "category": "Seal", "description": "API plan seal system", "life_cycle_status": "Active"},
  {"id": 459, "Part-Number": "OP-334934", "category": "Actuator", "description": "Guided cylinder anti-rotation", "life_cycle_status": "Active"},
  {"id": 460, "Part-Number": "GL-778967", "category": "Compressor", "description": "Oxygen compressor oil-free", "life_cycle_status": "Active"},
  {"id": 461, "Part-Number": "HY-889934", "category": "Valve", "description": "Cryogenic gate valve extended stem", "life_cycle_status": "Active"},
  {"id": 462, "Part-Number": "ME-556967", "category": "Connector", "description": "Hydraulic adapter tee branch", "life_cycle_status": "Active"},
  {"id": 463, "Part-Number": "TH-112934", "category": "Sensor", "description": "Potentiometric position sensor", "life_cycle_status": "Active"},
  {"id": 464, "Part-Number": "PR-112934", "category": "Pipe", "description": "Elbow butt weld long radius", "life_cycle_status": "Active"},
  {"id": 465, "Part-Number": "HY-778967", "category": "Filter", "description": "Adsorption filter activated alumina", "life_cycle_status": "Active"},
  {"id": 466, "Part-Number": "AE-889967", "category": "Pump", "description": "Can type pump vertical inline", "life_cycle_status": "Active"},
  {"id": 467, "Part-Number": "ST-445967", "category": "Regulator", "description": "Semiconductor grade regulator", "life_cycle_status": "Active"},
  {"id": 468, "Part-Number": "EN-445967", "category": "Seal", "description": "Mixer seal agitator type", "life_cycle_status": "Active"},
  {"id": 469, "Part-Number": "OP-889934", "category": "Actuator", "description": "Tandem cylinder high force", "life_cycle_status": "Active"},
  {"id": 470, "Part-Number": "GL-112934", "category": "Compressor", "description": "Argon compressor inert gas", "life_cycle_status": "Active"},
  {"id": 471, "Part-Number": "HY-112945", "category": "Valve", "description": "Metal seated ball valve fireproof", "life_cycle_status": "Active"},
  {"id": 472, "Part-Number": "ME-667967", "category": "Connector", "description": "Hydraulic adapter cross", "life_cycle_status": "Active"},
  {"id": 473, "Part-Number": "TH-667967", "category": "Sensor", "description": "Resolver rotary position", "life_cycle_status": "Active"},
  {"id": 474, "Part-Number": "PR-889967", "category": "Pipe", "description": "Tee butt weld equal", "life_cycle_status": "Active"},
  {"id": 475, "Part-Number": "HY-667934", "category": "Filter", "description": "Desiccant dryer filter twin tower", "life_cycle_status": "Active"},
  {"id": 476, "Part-Number": "AE-445967", "category": "Pump", "description": "Non-clog pump open impeller", "life_cycle_status": "Active"},
  {"id": 477, "Part-Number": "ST-334934", "category": "Regulator", "description": "Dome loaded back pressure", "life_cycle_status": "Active"},
  {"id": 478, "Part-Number": "EN-998967", "category": "Seal", "description": "Compressor seal labyrinth", "life_cycle_status": "Active"},
  {"id": 479, "Part-Number": "OP-445967", "category": "Actuator", "description": "Duplex cylinder dual piston", "life_cycle_status": "Active"},
  {"id": 480, "Part-Number": "GL-889967", "category": "Compressor", "description": "Ethylene compressor polymerization", "life_cycle_status": "Active"},
  {"id": 481, "Part-Number": "HY-667945", "category": "Valve", "description": "Subsea gate valve actuated", "life_cycle_status": "Active"},
  {"id": 482, "Part-Number": "ME-223934", "category": "Connector", "description": "Bulkhead adapter panel mount", "life_cycle_status": "Active"},
  {"id": 483, "Part-Number": "TH-998967", "category": "Sensor", "description": "Synchro rotary transformer", "life_cycle_status": "Active"},
  {"id": 484, "Part-Number": "PR-667967", "category": "Pipe", "description": "Reducer butt weld concentric", "life_cycle_status": "Active"},
  {"id": 485, "Part-Number": "HY-889945", "category": "Filter", "description": "Thermal swing adsorption filter", "life_cycle_status": "Active"},
  {"id": 486, "Part-Number": "AE-334934", "category": "Pump", "description": "Sealless pump canned motor", "life_cycle_status": "Active"},
  {"id": 487, "Part-Number": "ST-778967", "category": "Regulator", "description": "High vacuum pressure regulator", "life_cycle_status": "Active"},
  {"id": 488, "Part-Number": "EN-223934", "category": "Seal", "description": "Steam joint rotary seal", "life_cycle_status": "Active"},
  {"id": 489, "Part-Number": "OP-223934", "category": "Actuator", "description": "Impact cylinder quick exhaust", "life_cycle_status": "Active"},
  {"id": 490, "Part-Number": "GL-667967", "category": "Compressor", "description": "Propane compressor hydrocarbon", "life_cycle_status": "Active"},
  {"id": 491, "Part-Number": "HY-334945", "category": "Valve", "description": "Axial flow check valve nozzle", "life_cycle_status": "Active"},
  {"id": 492, "Part-Number": "ME-889934", "category": "Connector", "description": "Run tee branch hydraulic", "life_cycle_status": "Active"},
  {"id": 493, "Part-Number": "TH-445967", "category": "Sensor", "description": "Inductive position sensor analog", "life_cycle_status": "Active"},
  {"id": 494, "Part-Number": "PR-445934", "category": "Pipe", "description": "Reducer butt weld eccentric", "life_cycle_status": "Active"},
  {"id": 495, "Part-Number": "HY-112956", "category": "Filter", "description": "Molecular sieve filter adsorbent", "life_cycle_status": "Active"},
  {"id": 496, "Part-Number": "AE-556934", "category": "Pump", "description": "High head pump multistage centrifugal", "life_cycle_status": "Active"},
  {"id": 497, "Part-Number": "ST-112934", "category": "Regulator", "description": "Cryogenic fluid pressure regulator", "life_cycle_status": "Active"},
  {"id": 498, "Part-Number": "EN-556934", "category": "Seal", "description": "Bearing isolator seal", "life_cycle_status": "Active"},
  {"id": 499, "Part-Number": "OP-998934", "category": "Actuator", "description": "Cushioned cylinder adjustable", "life_cycle_status": "Active"},
  {"id": 500, "Part-Number": "GL-998967", "category": "Compressor", "description": "Propylene compressor petrochemical", "life_cycle_status": "Active"}
]

@app.route("/")
def home():
    return jsonify({"message": "Welcome to Dummy Product API"}), 200

@app.route("/products", methods=["GET"])
def get_products():
    api_key = request.headers.get("x-api-key")
    if not api_key:
        return jsonify({"error": "API key missing"}), 401

    if api_key != VALID_API_KEY:
        return jsonify({"error": "Invalid API key"}), 401

    category = request.args.get("category")
    if category:
        filtered = [p for p in PRODUCTS if p["category"].lower() == category.lower()]
        return jsonify(filtered), 200

    return jsonify(PRODUCTS), 200

@app.route("/product-api", methods=["GET"])
def get_product():
    api_key = request.headers.get("x-api-key")
    if not api_key:
        return jsonify({"error": "API key missing"}), 401

    if api_key != VALID_API_KEY:
        return jsonify({"error": "Invalid API key"}), 401

    category = request.args.get("category")
    if category:
        filtered = [p for p in 500_Products if p["category"].lower() == category.lower()]
        return jsonify(filtered), 200

    return jsonify(500_Products), 200

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)



